apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: healthapp
  name: healthapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: healthapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: healthapp
    spec:
      containers:
      - image: vishalbiyani/healthapp
        name: healthapp
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 1  
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 2
          timeoutSeconds: 1    
        ports:
        - containerPort: 8080
          protocol: TCP
